core/pom.xml, core/src/main/java/org/infinispan/protostream/annotations/ProtoDoc.java, core/src/main/java/org/infinispan/protostream/annotations/impl/DocumentationExtractor.java, core/src/main/java/org/infinispan/protostream/annotations/impl/MarshallerCodeGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoEnumTypeMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoEnumValueMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoFieldMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoMessageTypeMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoTypeMetadata.java, core/src/main/resources/features.xml, core/src/test/java/org/infinispan/protostream/annotations/impl/testdomain/TestClass.java, core/src/test/java/org/infinispan/protostream/annotations/impl/testdomain/TestEnum.java, sample-domain-implementation/src/main/java/org/infinispan/protostream/sampledomain/Note.java
Jira: https://issues.jboss.org/browse/ISPN-4006
=> ISPN-4006 Make protostream OSGI/Karaf friendly by providing a features.xml

core/pom.xml, core/src/main/resources/features.xml, parent/pom.xml
Jira: https://issues.jboss.org/browse/ISPN-5138
=> ISPN-5138 Make protostream an uberjar

core/src/main/java/org/infinispan/protostream/impl/AnnotatedDescriptorImpl.java, core/src/main/java/org/infinispan/protostream/impl/ProtoStreamWriterImpl.java, core/src/main/java/org/infinispan/protostream/impl/RawProtoStreamWriterImpl.java, core/src/test/java/org/infinispan/protostream/config/AnnotationConfigTest.java, core/src/test/java/org/infinispan/protostream/impl/parser/impl/DescriptorsTest.java
Jira: https://issues.jboss.org/browse/ISPN-5203
=> ISPN-5203 Protostream annotation attributes that do not have a default value should be required

core/src/test/java/org/infinispan/protostream/MarshallingTest.java, core/src/test/java/org/infinispan/protostream/ProtobufParserTest.java, core/src/test/java/org/infinispan/protostream/WrappingTest.java, core/src/test/java/org/infinispan/protostream/domain/Address.java, core/src/test/java/org/infinispan/protostream/domain/marshallers/AddressMarshaller.java, core/src/test/java/org/infinispan/protostream/impl/UnknownFieldSetImplTest.java, core/src/test/java/org/infinispan/protostream/test/AnnotationsPerformanceTest.java, core/src/test/java/org/infinispan/protostream/test/PerformanceTest.java, sample-domain-definition/src/main/resources/sample_bank_account/bank.proto, sample-domain-implementation/src/main/java/org/infinispan/protostream/sampledomain/Address.java
Needed to test aggregation functions on numbers in embedded entities.
=> ISPN-5788 Add new numeric field to Address

core/src/main/java/org/infinispan/protostream/BaseMarshaller.java, core/src/main/java/org/infinispan/protostream/EnumMarshaller.java, core/src/main/java/org/infinispan/protostream/FileDescriptorSource.java, core/src/main/java/org/infinispan/protostream/ImmutableSerializationContext.java, core/src/main/java/org/infinispan/protostream/MessageMarshaller.java, core/src/main/java/org/infinispan/protostream/ProtobufUtil.java, core/src/main/java/org/infinispan/protostream/SerializationContext.java, core/src/main/java/org/infinispan/protostream/WrappedMessage.java, core/src/main/java/org/infinispan/protostream/annotations/ProtoSchemaBuilder.java, core/src/main/java/org/infinispan/protostream/annotations/impl/MarshallerCodeGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoFieldMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoMessageTypeMetadata.java, core/src/main/java/org/infinispan/protostream/descriptors/FileDescriptor.java, core/src/main/java/org/infinispan/protostream/impl/ProtoStreamReaderImpl.java, core/src/main/java/org/infinispan/protostream/impl/ProtoStreamWriterImpl.java, core/src/main/java/org/infinispan/protostream/impl/SerializationContextImpl.java, core/src/main/java/org/infinispan/protostream/impl/parser/SquareProtoParser.java, core/src/test/java/org/infinispan/protostream/MarshallingTest.java, core/src/test/java/org/infinispan/protostream/ProtobufParserTest.java, core/src/test/java/org/infinispan/protostream/ProtobufUtilTest.java, core/src/test/java/org/infinispan/protostream/WrappingTest.java, core/src/test/java/org/infinispan/protostream/annotations/impl/ProtoSchemaBuilderTest.java, core/src/test/java/org/infinispan/protostream/domain/User.java, core/src/test/java/org/infinispan/protostream/domain/marshallers/UserMarshaller.java, core/src/test/java/org/infinispan/protostream/impl/SerializationContextImplTest.java, core/src/test/java/org/infinispan/protostream/impl/UnknownFieldSetImplTest.java, sample-domain-definition/src/main/resources/sample_bank_account/bank.proto, sample-domain-implementation/src/main/java/org/infinispan/protostream/sampledomain/User.java, sample-domain-implementation/src/main/java/org/infinispan/protostream/sampledomain/marshallers/UserMarshaller.java
https://issues.jboss.org/browse/IPROTO-26
https://issues.jboss.org/browse/IPROTO-23
https://issues.jboss.org/browse/IPROTO-24
https://issues.jboss.org/browse/IPROTO-25
https://issues.jboss.org/browse/IPROTO-27
=> IPROTO-26 Add support for java.time.Instant

core/src/main/java/org/infinispan/protostream/impl/ProtoStreamReaderImpl.java, core/src/test/java/org/infinispan/protostream/MarshallingTest.java, core/src/test/java/org/infinispan/protostream/domain/Account.java, core/src/test/java/org/infinispan/protostream/domain/marshallers/AccountMarshaller.java, core/src/test/java/org/infinispan/protostream/domain/marshallers/CurrencyMarshaller.java, core/src/test/java/org/infinispan/protostream/domain/marshallers/MarshallerRegistration.java, sample-domain-definition/src/main/resources/sample_bank_account/bank.proto
https://issues.jboss.org/browse/IPROTO-33
=> IPROTO-33 ClassCastException with Array of Enums

core/pom.xml, core/src/main/java/org/infinispan/protostream/ProtobufParser.java, core/src/main/java/org/infinispan/protostream/ProtobufUtil.java, core/src/main/java/org/infinispan/protostream/TagHandler.java, core/src/main/java/org/infinispan/protostream/impl/UnknownFieldSetImpl.java, core/src/test/java/org/infinispan/protostream/ProtobufParserTest.java, core/src/test/java/org/infinispan/protostream/ProtobufUtilTest.java, core/src/test/java/org/infinispan/protostream/domain/Account.java, core/src/test/java/org/infinispan/protostream/domain/Address.java, core/src/test/java/org/infinispan/protostream/domain/User.java, core/src/test/java/org/infinispan/protostream/domain/marshallers/AccountMarshaller.java, core/src/test/java/org/infinispan/protostream/domain/marshallers/AddressMarshaller.java, parent/pom.xml, sample-domain-definition/src/main/resources/sample_bank_account/bank.proto
https://issues.jboss.org/browse/IPROTO-32
=> IPROTO-32 Implement conversion from JSON to protobuf

core/src/main/java/org/infinispan/protostream/ProtobufUtil.java, core/src/test/java/org/infinispan/protostream/ProtobufUtilTest.java
https://issues.jboss.org/browse/IPROTO-34
=> IPROTO-34 Protobuf/Json mapping generates invalid json

core/src/main/java/org/infinispan/protostream/ImmutableSerializationContext.java, core/src/main/java/org/infinispan/protostream/annotations/ProtoSchemaBuilder.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoSchemaGenerator.java, core/src/main/java/org/infinispan/protostream/impl/MessageMarshallerDelegate.java, core/src/main/java/org/infinispan/protostream/impl/SerializationContextImpl.java, core/src/main/resources/features.xml, core/src/main/resources/org/infinispan/protostream/message-wrapping.proto
https://issues.jboss.org/browse/IPROTO-38
=> IPROTO-38 ProtoSchemaGenerator fails in Karaf: CNFE: org.infinispan.protostream.RawProtobufMarshaller

core/pom.xml, core/src/main/java/org/infinispan/protostream/FileDescriptorSource.java, core/src/main/java/org/infinispan/protostream/annotations/ProtoDoc.java, core/src/main/java/org/infinispan/protostream/annotations/impl/DocumentationExtractor.java, core/src/main/java/org/infinispan/protostream/config/ConfigurationImpl.java, core/src/main/java/org/infinispan/protostream/descriptors/AnnotatedDescriptor.java, core/src/main/java/org/infinispan/protostream/descriptors/AnnotationElement.java, core/src/main/java/org/infinispan/protostream/descriptors/Descriptor.java, core/src/main/java/org/infinispan/protostream/descriptors/FieldDescriptor.java, core/src/main/java/org/infinispan/protostream/descriptors/FileDescriptor.java, core/src/main/java/org/infinispan/protostream/descriptors/ResolutionContext.java, core/src/main/java/org/infinispan/protostream/descriptors/namespace/package-info.java, core/src/main/java/org/infinispan/protostream/impl/AnnotatedDescriptorImpl.java, core/src/main/java/org/infinispan/protostream/impl/SerializationContextImpl.java, core/src/main/java/org/infinispan/protostream/impl/parser/AnnotationLexer.java, core/src/main/java/org/infinispan/protostream/impl/parser/SquareProtoParser.java, core/src/main/java/org/infinispan/protostream/impl/parser/mappers/Mappers.java, core/src/test/java/org/infinispan/protostream/impl/parser/DescriptorsTest.java, core/src/test/java/org/infinispan/protostream/impl/parser/impl/DescriptorsTest.java, parent/pom.xml, pom.xml, sample-domain-definition/pom.xml, sample-domain-implementation/pom.xml
https://issues.jboss.org/browse/IPROTO-48
https://issues.jboss.org/browse/IPROTO-49
=> IPROTO-48 Ignore unknown protobuf documentation annotations

core/src/main/java/org/infinispan/protostream/descriptors/AnnotationElement.java, core/src/main/java/org/infinispan/protostream/impl/AnnotatedDescriptorImpl.java
https://issues.jboss.org/browse/IPROTO-50
* print the current value vs whatever was expected for attributes of
annotations the do not pass validation
* implement a human readable toString() for AnnotationElements
=> IPROTO-50 Provide better error messages for annotation validation

core/src/main/java/org/infinispan/protostream/BaseMarshaller.java, core/src/main/java/org/infinispan/protostream/EnumMarshaller.java, core/src/main/java/org/infinispan/protostream/ImmutableSerializationContext.java, core/src/main/java/org/infinispan/protostream/MessageMarshaller.java, core/src/main/java/org/infinispan/protostream/ProtobufUtil.java, core/src/main/java/org/infinispan/protostream/RawProtobufMarshaller.java, core/src/main/java/org/infinispan/protostream/TagHandler.java, core/src/main/java/org/infinispan/protostream/WrappedMessage.java, core/src/main/java/org/infinispan/protostream/annotations/ProtoSchemaBuilder.java, core/src/main/java/org/infinispan/protostream/annotations/impl/MarshallerCodeGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoMessageTypeMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/package-info.java, core/src/main/java/org/infinispan/protostream/descriptors/JavaType.java, core/src/main/java/org/infinispan/protostream/descriptors/Type.java, parent/pom.xml
https://issues.jboss.org/browse/IPROTO-69
=>  IPROTO-69 Upgrade gson to 2.8.2

parent/pom.xml
https://issues.jboss.org/browse/IPROTO-70
=> IPROTO-70 Upgrade protobuf-java to 3.6.1

.travis.yml, core/pom.xml, parent/pom.xml
* Build with JDK 8,9,10,11; both Oracle and OpenJDK are used
https://issues.jboss.org/browse/IPROTO-71
=> IPROTO-71 Fix compat issue with JDK 9,10,11 and add CI testing for them

core/src/main/java/org/infinispan/protostream/ProtobufUtil.java, core/src/test/java/org/infinispan/protostream/MarshallingTest.java, core/src/test/java/org/infinispan/protostream/ProtobufUtilTest.java, core/src/test/java/org/infinispan/protostream/domain/Account.java, core/src/test/java/org/infinispan/protostream/domain/marshallers/AccountMarshaller.java, sample-domain-definition/src/main/resources/sample_bank_account/bank.proto
https://issues.jboss.org/browse/IPROTO-75
=> IPROTO-75 Conversion from JSON to Protobuf fails when using required non-scalar fields

core/pom.xml, core/src/main/java/org/infinispan/protostream/Version.java, core/src/main/java/org/infinispan/protostream/annotations/impl/MarshallerCodeGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoSchemaGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoTypeMetadata.java
https://issues.jboss.org/browse/IPROTO-79
=> IPROTO-79 All fields in generated marshallers should be private

core/src/main/java/org/infinispan/protostream/annotations/impl/ImportedProtoTypeMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoEnumTypeMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoEnumValueMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoMessageTypeMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoSchemaGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoTypeMetadata.java, core/src/test/java/org/infinispan/protostream/annotations/impl/ProtoSchemaBuilderTest.java
https://issues.jboss.org/browse/IPROTO-84
https://issues.jboss.org/browse/IPROTO-85
=>  IPROTO-85 ClassCastException with enum imported from external schema when using ProtoSchemaBuilder

processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/AnnotatedClassScanner.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/AutoProtoSchemaBuilderAnnotationProcessor.java, processor/src/test/java/org/infinispan/protostream/annotations/impl/processor/tests/AutoProtoSchemaBuilderTest.java
https://issues.jboss.org/browse/IPROTO-92
=> IPROTO-92 AnnotatedClassScanner.isPublicElement does not work

core/src/main/java/org/infinispan/protostream/MessageMarshaller.java, core/src/main/java/org/infinispan/protostream/annotations/impl/AbstractMarshallerCodeGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoFieldMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoMessageTypeMetadata.java, core/src/main/java/org/infinispan/protostream/descriptors/FieldDescriptor.java, core/src/main/java/org/infinispan/protostream/descriptors/JavaType.java, core/src/main/java/org/infinispan/protostream/descriptors/Type.java, core/src/test/java/org/infinispan/protostream/domain/Note.java, core/src/test/java/org/infinispan/protostream/domain/marshallers/NoteMarshaller.java, core/src/test/java/org/infinispan/protostream/test/AnnotationsPerformanceTest.java
https://issues.jboss.org/browse/IPROTO-51
https://issues.jboss.org/browse/IPROTO-80
https://issues.jboss.org/browse/IPROTO-95
=> IPROTO-51ProtoSchemaBuilder fails on required property of type bytes

core/src/main/java/org/infinispan/protostream/annotations/ProtoReserved.java, core/src/main/java/org/infinispan/protostream/annotations/ProtoReservedStatements.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoEnumTypeMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoMessageTypeMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ReservedProcessor.java, core/src/main/java/org/infinispan/protostream/annotations/impl/types/ReflectionClassFactory.java, core/src/main/java/org/infinispan/protostream/annotations/impl/types/XElement.java, core/src/test/java/org/infinispan/protostream/annotations/impl/ProtoSchemaBuilderTest.java, core/src/test/java/org/infinispan/protostream/annotations/impl/ReservedProcessorTest.java, core/src/test/java/org/infinispan/protostream/annotations/impl/testdomain/TestClass.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/types/MirrorClassFactory.java, processor/src/test/java/org/infinispan/protostream/annotations/impl/processor/tests/AutoProtoSchemaBuilderTest.java
https://issues.jboss.org/browse/IPROTO-11
=> IPROTO-11 Implement reserved fields

core/src/main/java/org/infinispan/protostream/annotations/ProtoFactory.java, core/src/main/java/org/infinispan/protostream/annotations/impl/AbstractMarshallerCodeGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/BaseProtoSchemaGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ImportedProtoTypeMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/MarshallerByteCodeGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoEnumTypeMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoEnumValueMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoFieldMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoMessageTypeMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/types/ReflectionClassFactory.java, core/src/main/java/org/infinispan/protostream/annotations/impl/types/XClass.java, core/src/main/java/org/infinispan/protostream/annotations/impl/types/XExecutable.java, core/src/test/java/org/infinispan/protostream/annotations/impl/ProtoSchemaBuilderTest.java, integrationtests/pom.xml, parent/pom.xml, pom.xml, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/AnnotatedClassScanner.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/AnnotationBasedImportedProtoTypeMetadata.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/AutoProtoSchemaBuilderAnnotationProcessor.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/MarshallerSourceCodeGenerator.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/types/MirrorClassFactory.java, processor/src/test/java/org/infinispan/protostream/annotations/impl/processor/tests/AutoProtoSchemaBuilderTest.java, sample-domain-definition/pom.xml, sample-domain-implementation/pom.xml
https://issues.jboss.org/browse/IPROTO-94
=> IPROTO-94 Marshalling of immutable objects

core/src/main/java/org/infinispan/protostream/annotations/ProtoSchemaBuilder.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoMessageTypeMetadata.java, core/src/test/java/org/infinispan/protostream/annotations/impl/ProtoSchemaBuilderTest.java, core/src/test/java/org/infinispan/protostream/test/ExpectedLogMessage.java, processor/src/test/java/org/infinispan/protostream/annotations/impl/processor/tests/AutoProtoSchemaBuilderTest.java
https://issues.jboss.org/browse/IPROTO-99
=> IPROTO-99 Ability to define an empty proto message via Pojo annotations

core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoMessageTypeMetadata.java, core/src/test/java/org/infinispan/protostream/annotations/impl/ProtoSchemaBuilderTest.java
https://issues.jboss.org/browse/IPROTO-103
=> IPROTO-103 Not possible to have @ProtoField of type List<byte[]>

core/src/test/java/org/infinispan/protostream/annotations/impl/ProtoSchemaBuilderTest.java, processor/src/test/java/org/infinispan/protostream/annotations/impl/processor/tests/AutoProtoSchemaBuilderTest.java
* this issue was happening in 4.3.0.Alpha6 and was fixed since then due to the many refactorings required by IPROTO-94
https://issues.jboss.org/browse/IPROTO-100
=> IPROTO-100 Add test to demonstrate the issue is fixed

core/src/main/java/org/infinispan/protostream/annotations/impl/AbstractMarshallerCodeGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoMessageTypeMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/types/ReflectionClassFactory.java, core/src/main/java/org/infinispan/protostream/annotations/impl/types/XMember.java, core/src/main/java/org/infinispan/protostream/annotations/impl/types/XMethod.java, core/src/test/java/org/infinispan/protostream/annotations/impl/ProtoSchemaBuilderTest.java, core/src/test/java/org/infinispan/protostream/annotations/impl/testdomain/TestArraysAndCollectionsClass.java, core/src/test/java/org/infinispan/protostream/annotations/impl/testdomain/TestArraysAndCollectionsClass2.java, core/src/test/java/org/infinispan/protostream/annotations/impl/testdomain/TestBaseClass.java, core/src/test/java/org/infinispan/protostream/domain/Note.java, core/src/test/java/org/infinispan/protostream/domain/User.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/types/MirrorClassFactory.java, processor/src/test/java/org/infinispan/protostream/annotations/impl/processor/tests/AutoProtoSchemaBuilderTest.java
https://issues.jboss.org/browse/IPROTO-102
https://issues.jboss.org/browse/IPROTO-107
=> T iproto 102 m

core/src/main/java/org/infinispan/protostream/annotations/ProtoSchemaBuilder.java, core/src/main/java/org/infinispan/protostream/annotations/impl/MarshallerByteCodeGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/OriginatingClasses.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoEnumTypeMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoFieldMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoTypeMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/RuntimeProtoSchemaGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/types/ReflectionClassFactory.java, core/src/main/java/org/infinispan/protostream/annotations/impl/types/XClass.java, core/src/main/java/org/infinispan/protostream/annotations/impl/types/XElement.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/AnnotatedClassScanner.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/MarshallerSourceCodeGenerator.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/types/MirrorClassFactory.java
https://issues.jboss.org/browse/IPROTO-108
=> T iproto 108 m

core/pom.xml, parent/pom.xml, processor/pom.xml, processor/src/test/java/org/infinispan/protostream/annotations/impl/processor/tests/AutoProtoSchemaBuilderTest.java, processor/src/test/java/org/infinispan/protostream/annotations/impl/processor/tests/testdomain/SimpleClass.java, processor/src/test/java/org/infinispan/protostream/annotations/impl/processor/tests/testdomain/SimpleEnum.java
https://issues.jboss.org/browse/IPROTO-110
=> IPROTO-110 Protostream should not expose dependencies on the artifacts it already includes in the uberjar

core/src/main/java/org/infinispan/protostream/annotations/impl/ImportedProtoTypeMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoEnumTypeMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/types/ReflectionClassFactory.java, core/src/test/java/org/infinispan/protostream/annotations/impl/ProtoSchemaBuilderTest.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/JavacCompilationTest.java
https://issues.jboss.org/browse/IPROTO-113
=> IPROTO-113 Generated marshallers for nested enums don't compile

core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoMessageTypeMetadata.java, core/src/test/java/org/infinispan/protostream/annotations/impl/testdomain/Simple.java, core/src/test/java/org/infinispan/protostream/annotations/impl/testdomain/TestEnum.java
https://issues.redhat.com/browse/IPROTO-132
=> IPROTO-132 Enum classes with abstract methods don't compile

core/src/main/java/org/infinispan/protostream/descriptors/AnnotatedDescriptor.java, core/src/main/resources/org/infinispan/protostream/message-wrapping.proto, parent/pom.xml, sample-domain-definition/src/main/resources/sample_bank_account/bank.proto
https://issues.redhat.com/browse/IPROTO-142
=> IPROTO-142 Make some fields in bank.proto @SortableField

parent/pom.xml
https://issues.redhat.com/browse/IPROTO-143
=> IPROTO-143 Update protobuf-java to 3.12.2

parent/pom.xml
https://issues.redhat.com/browse/ISPN-12001
=> ISPN-12001 Add jboss-parent

parent/pom.xml
https://issues.redhat.com/browse/ISPN-12001
=> [4.3.x] ISPN-12001 Add jboss-parent

core/src/main/java/org/infinispan/protostream/annotations/AutoProtoSchemaBuilder.java
https://issues.redhat.com/browse/ISPN-12036
=> ISPN-12036 Default to generating AutoProtoSchemaBuilder service files

core/src/main/java/org/infinispan/protostream/annotations/ProtoSchemaBuilderException.java, core/src/main/java/org/infinispan/protostream/annotations/impl/BaseProtoSchemaGenerator.java, core/src/main/java/org/infinispan/protostream/impl/parser/mappers/Mappers.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/AutoProtoSchemaBuilderAnnotationProcessor.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/MarshallerSourceCodeGenerator.java
https://issues.redhat.com/browse/IPROTO-164
=> IPROTO-164 All warnings from sources generated by the protostream processor should be silenced

parent/pom.xml
https://issues.redhat.com/browse/IPROTO-166
=> IPROTO-166 Bump junit from 4.13 to 4.13.1

core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoMessageTypeMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/types/ReflectionClassFactory.java, core/src/test/java/org/infinispan/protostream/annotations/impl/ProtoSchemaBuilderTest.java, processor/src/test/java/org/infinispan/protostream/annotations/impl/processor/tests/AutoProtoSchemaBuilderTest.java
https://issues.redhat.com/browse/IPROTO-168
=> IPROTO-168 ReflectionClass.getMethod finds only public methods

core/pom.xml, core/src/main/java/org/infinispan/protostream/annotations/ProtoSchemaBuilder.java, core/src/main/java/org/infinispan/protostream/annotations/impl/AbstractMarshallerCodeGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/BaseProtoSchemaGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/HasProtoSchema.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoMessageTypeMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoTypeMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/RuntimeProtoSchemaGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/types/ReflectionClassFactory.java, core/src/main/java/org/infinispan/protostream/annotations/impl/types/XTypeFactory.java, core/src/test/java/org/infinispan/protostream/annotations/impl/ProtoSchemaBuilderTest.java, core/src/test/java/org/infinispan/protostream/annotations/impl/types/ReflectionClassFactoryTest.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/AnnotatedClassScanner.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/AutoProtoSchemaBuilderAnnotationProcessor.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/CompileTimeImportedProtoTypeMetadata.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/CompileTimeProtoMessageTypeMetadata.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/CompileTimeProtoSchemaGenerator.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/DangerousActions.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/MarshallerSourceCodeGenerator.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/OriginatingClasses.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/types/MirrorClassFactory.java, processor/src/test/java/org/infinispan/protostream/annotations/impl/processor/tests/AutoProtoSchemaBuilderTest.java
https://issues.redhat.com/browse/IPROTO-163
=> IPROTO-163 Remove javax.annotation-api dependency from core

README.md, core/pom.xml, core/src/main/java/org/infinispan/protostream/annotations/impl/RuntimeProtoSchemaGenerator.java, core/src/main/resources/features.xml, parent/pom.xml, sample-domain-definition/pom.xml, sample-domain-implementation/pom.xml
https://issues.redhat.com/browse/IPROTO-173
=> IPROTO-173 Remove osgi support 

parent/pom.xml
https://issues.redhat.com/browse/IPROTO-145
=> IPROTO-145 Upgrade javax.annotation-api to 1.3.2

core/src/main/java/org/infinispan/protostream/annotations/ProtoAdapter.java, core/src/main/java/org/infinispan/protostream/annotations/ProtoEnumValue.java, core/src/main/java/org/infinispan/protostream/annotations/ProtoReserved.java, core/src/main/java/org/infinispan/protostream/annotations/impl/BaseProtoSchemaGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoEnumTypeMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoTypeMetadata.java, core/src/test/java/org/infinispan/protostream/annotations/impl/ProtoSchemaBuilderTest.java, core/src/test/java/org/infinispan/protostream/annotations/impl/testdomain/Simple.java, core/src/test/java/org/infinispan/protostream/annotations/impl/testdomain/UUIDAdapter.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/AnnotationProcessorCompilationTest.java, integrationtests/src/test/resources/org/infinispan/protostream/integrationtests/processor/MarshallExternals.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/CompileTimeProtoSchemaGenerator.java
https://issues.redhat.com/browse/IPROTO-171
=> IPROTO-171 Implement ProtoAdapter for enums

core/pom.xml
https://issues.redhat.com/browse/IPROTO-177
=> IPROTO-177 Protobuf Java is not fully shaded

core/src/main/java/org/infinispan/protostream/ProtobufUtil.java, core/src/main/java/org/infinispan/protostream/impl/ByteArrayOutputStreamEx.java
https://issues.redhat.com/browse/IPROTO-191
=> IPROTO-191 ByteArrayOutputStreamEx.getByteBuffer method should be synchronized

core/src/main/java/org/infinispan/protostream/BaseMarshaller.java, core/src/main/java/org/infinispan/protostream/DescriptorParser.java, core/src/main/java/org/infinispan/protostream/MessageMarshaller.java, core/src/main/java/org/infinispan/protostream/UnknownFieldSetHandler.java, core/src/main/java/org/infinispan/protostream/WrappedMessage.java, core/src/main/java/org/infinispan/protostream/annotations/ProtoFactory.java, core/src/main/java/org/infinispan/protostream/annotations/impl/MarshallerByteCodeGenerator.java, core/src/main/java/org/infinispan/protostream/impl/SerializationContextImpl.java, core/src/main/java/org/infinispan/protostream/impl/parser/SquareProtoParser.java, core/src/main/resources/org/infinispan/protostream/message-wrapping.proto, core/src/test/java/org/infinispan/protostream/impl/TopLevelArrayTest.java
https://issues.redhat.com/browse/IPROTO-192
https://issues.redhat.com/browse/IPROTO-183
https://issues.redhat.com/browse/IPROTO-181
=> IPROTO-192 Deprecate DescriptorParser interface

core/src/main/java/org/infinispan/protostream/ImmutableSerializationContext.java, core/src/main/java/org/infinispan/protostream/ProtobufUtil.java, core/src/main/java/org/infinispan/protostream/SerializationContext.java, core/src/main/java/org/infinispan/protostream/WrappedMessage.java, core/src/main/java/org/infinispan/protostream/impl/JsonUtils.java, core/src/main/java/org/infinispan/protostream/impl/SerializationContextImpl.java, core/src/test/java/org/infinispan/protostream/impl/GenericObjectTest.java, core/src/test/java/org/infinispan/protostream/impl/SerializationContextImplTest.java
https://issues.redhat.com/browse/IPROTO-56
The approach is very similar to Gustavo's initial proposal but without the limitations ( https://github.com/infinispan/protostream/pull/37 )
=> IPROTO-56 Support for dynamic models

core/src/main/java/org/infinispan/protostream/annotations/impl/AbstractMarshallerCodeGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/BaseProtoSchemaGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/MarshallerByteCodeGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoFieldMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoMessageTypeMetadata.java, core/src/main/java/org/infinispan/protostream/containers/IndexedElementContainer.java, core/src/main/java/org/infinispan/protostream/containers/IndexedElementContainerAdapter.java, core/src/main/java/org/infinispan/protostream/containers/IterableElementContainer.java, core/src/main/java/org/infinispan/protostream/containers/IterableElementContainerAdapter.java, core/src/test/java/org/infinispan/protostream/annotations/impl/ProtoSchemaBuilderTest.java, core/src/test/java/org/infinispan/protostream/annotations/impl/testdomain/AddressAdapter.java, core/src/test/java/org/infinispan/protostream/impl/ElementContainerTest.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/AnnotationProcessorCompilationTest.java, integrationtests/src/test/resources/org/infinispan/protostream/integrationtests/processor/TestElementContainer.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/MarshallerSourceCodeGenerator.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/types/HasModelElement.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/types/MirrorTypeFactory.java
https://issues.redhat.com/browse/IPROTO-195
=> IPROTO-195 Generate proper initializers for variables corresponding to required primitive fields when @ProtoFactory is used

pom.xml, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/MarshallerSourceCodeGenerator.java, types/pom.xml, types/src/main/java/org/infinispan/protostream/types/java/ArrayListAdapter.java, types/src/main/java/org/infinispan/protostream/types/java/BigDecimalAdapter.java, types/src/main/java/org/infinispan/protostream/types/java/BigIntegerAdapter.java, types/src/main/java/org/infinispan/protostream/types/java/CommonContainerTypes.java, types/src/main/java/org/infinispan/protostream/types/java/CommonTypes.java, types/src/main/java/org/infinispan/protostream/types/java/HashSetAdapter.java, types/src/main/java/org/infinispan/protostream/types/java/IntArrayAdapter.java, types/src/main/java/org/infinispan/protostream/types/java/IntegerArrayAdapter.java, types/src/main/java/org/infinispan/protostream/types/java/UUIDAdapter.java, types/src/main/java/org/infinispan/protostream/types/protobuf/Any.java, types/src/main/java/org/infinispan/protostream/types/protobuf/AnySchema.java, types/src/main/java/org/infinispan/protostream/types/protobuf/BoolValue.java, types/src/main/java/org/infinispan/protostream/types/protobuf/BytesValue.java, types/src/main/java/org/infinispan/protostream/types/protobuf/DoubleValue.java, types/src/main/java/org/infinispan/protostream/types/protobuf/Duration.java, types/src/main/java/org/infinispan/protostream/types/protobuf/DurationSchema.java, types/src/main/java/org/infinispan/protostream/types/protobuf/Empty.java, types/src/main/java/org/infinispan/protostream/types/protobuf/EmptySchema.java, types/src/main/java/org/infinispan/protostream/types/protobuf/FloatValue.java, types/src/main/java/org/infinispan/protostream/types/protobuf/Int32Value.java, types/src/main/java/org/infinispan/protostream/types/protobuf/Int64Value.java, types/src/main/java/org/infinispan/protostream/types/protobuf/StringValue.java, types/src/main/java/org/infinispan/protostream/types/protobuf/Timestamp.java, types/src/main/java/org/infinispan/protostream/types/protobuf/TimestampSchema.java, types/src/main/java/org/infinispan/protostream/types/protobuf/UInt32Value.java, types/src/main/java/org/infinispan/protostream/types/protobuf/UInt64Value.java, types/src/main/java/org/infinispan/protostream/types/protobuf/WrappersSchema.java
https://issues.redhat.com/browse/IPROTO-194
https://issues.redhat.com/browse/IPROTO-44
https://issues.redhat.com/browse/IPROTO-198
=> IPROTO-194 Create a new protostream module providing support for marshalling common Java types

core/pom.xml, core/src/main/java/org/infinispan/protostream/MalformedProtobufException.java, core/src/main/java/org/infinispan/protostream/ProtobufParser.java, core/src/main/java/org/infinispan/protostream/ProtobufUtil.java, core/src/main/java/org/infinispan/protostream/RawProtoStreamReader.java, core/src/main/java/org/infinispan/protostream/RawProtoStreamWriter.java, core/src/main/java/org/infinispan/protostream/TagReader.java, core/src/main/java/org/infinispan/protostream/TagWriter.java, core/src/main/java/org/infinispan/protostream/annotations/impl/AbstractMarshallerCodeGenerator.java, core/src/main/java/org/infinispan/protostream/descriptors/WireType.java, core/src/main/java/org/infinispan/protostream/impl/Decoder.java, core/src/main/java/org/infinispan/protostream/impl/Encoder.java, core/src/main/java/org/infinispan/protostream/impl/ProtoStreamReaderImpl.java, core/src/main/java/org/infinispan/protostream/impl/ProtoStreamWriterImpl.java, core/src/main/java/org/infinispan/protostream/impl/TagReaderImpl.java, core/src/main/java/org/infinispan/protostream/impl/TagWriterImpl.java, core/src/main/java/org/infinispan/protostream/impl/UnknownFieldSetImpl.java, core/src/main/java/org/infinispan/protostream/impl/WireFormat.java, core/src/test/java/org/infinispan/protostream/ProtobufUtilTest.java, core/src/test/java/org/infinispan/protostream/impl/EncoderTest.java, core/src/test/java/org/infinispan/protostream/impl/SerializationContextImplTest.java, parent/pom.xml, pom.xml
* replace our usages of CodedInputStream and CodedOutputStream with
homegrown alternatives
https://issues.redhat.com/browse/IPROTO-200
=> IPROTO-200 Remove protobuf-java dependency

core/src/main/java/org/infinispan/protostream/ProtobufUtil.java, core/src/main/java/org/infinispan/protostream/descriptors/WireType.java, core/src/main/java/org/infinispan/protostream/impl/JsonUtils.java, core/src/main/java/org/infinispan/protostream/impl/UnknownFieldSetImpl.java
https://issues.redhat.com/browse/IPROTO-203
=> IPROTO-203 ProtobufUtil.fromCanonicalJSON fails with NPE when encountering an enum without a type id

types/src/main/java/org/infinispan/protostream/types/java/util/UUIDAdapter.java
https://issues.redhat.com/browse/IPROTO-211
=> IPROTO-211 UUIDAdapter has the incorrect Id

parent/pom.xml
Various upgrades
* Maven Compiler plugin  3.9.0
* Maven JavaDoc plugin   3.3.1
* Maven Resources plugin 3.2.0
* Maven Shade plugin     3.2.4
* Protobuf               3.19.4
* Mockito                4.3.1
* JBoss Logging          3.4.3.Final
* JBoss Logging Tools    2.2.1.Final
* Log4j                  2.17.1
* JBoss Marshalling      2.0.12.Final
* Javassist              3.28.0-GA
* Commons CLI            1.5.0
* Jackson                2.13.0
* Auto Service           1.0.1
=> Various upgrades

core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoEnumTypeMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoMessageTypeMetadata.java
https://issues.redhat.com/browse/IPROTO-227
=> IPROTO-227 Better errors

parent/pom.xml
https://issues.redhat.com/browse/IPROTO-231
Changed the property names to match the name in jboss-parent.
=> IPROTO-231 Upgrade jboss-parent to version 39

parent/pom.xml
Jackson 2.13.2
Log4j 2.17.2
https://issues.redhat.com/browse/IPROTO-234
https://issues.redhat.com/browse/IPROTO-235
=> Update Jackson and Log4j

core/src/main/java/org/infinispan/protostream/annotations/impl/AbstractMarshallerCodeGenerator.java, core/src/test/java/org/infinispan/protostream/annotations/impl/ProtoSchemaBuilderTest.java, processor/src/test/java/org/infinispan/protostream/annotations/impl/processor/tests/AutoProtoSchemaBuilderTest.java
https://issues.redhat.com/browse/IPROTO-218
=> IPROTO-218 Support uninitialized Date and Instant

Jenkinsfile, parent/pom.xml
maven-compiler-plugin -> 3.10.1
maven-surefire-plugin -> 3.0.0-M6
junit -> 4.13.2
https://issues.redhat.com/browse/IPROTO-238
=> IPROTO-238 Align dependencies version with Infinispan

Jenkinsfile-release, parent/pom.xml
* only a single profile is available
* do not manually open the repository before deploy
=> OSSRH - Remove staging profile

Jenkinsfile-release, parent/pom.xml, pom.xml
* Updated nexus-staging-plugin
* Remove unused property
=> OSSRH - Add SCM plugin

core/src/main/java/org/infinispan/protostream/annotations/ProtoField.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoFieldMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoMessageTypeMetadata.java, core/src/test/java/org/infinispan/protostream/annotations/impl/ProtoSchemaBuilderTest.java, core/src/test/java/org/infinispan/protostream/annotations/impl/testdomain/Simple.java
https://issues.jboss.org/browse/IPROTO-62
=> IPROTO-62 Implement annotation based schema generation support for 'oneof'

core/src/main/java/org/infinispan/protostream/annotations/impl/AbstractMarshallerCodeGenerator.java, core/src/test/java/org/infinispan/protostream/annotations/impl/ProtoSchemaBuilderTest.java, processor/src/test/java/org/infinispan/protostream/annotations/impl/processor/tests/AutoProtoSchemaBuilderTest.java
Backport the fix as it also affects released version.
=> IPROTO-218 Support uninitialized Date and Instant - Backport to 4.4.x branch

core/src/main/java/org/infinispan/protostream/impl/JsonUtils.java, core/src/test/java/org/infinispan/protostream/domain/User.java, integrationtests/pom.xml, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/UserSerializationContextInitializer.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/annotated_package/AnnotationOnPackageIntegrationTest.java
https://issues.redhat.com/browse/IPROTO-243
=> IPROTO-243 JSonUtil field 18 as boolean considered as a string

core/src/main/java/org/infinispan/protostream/ProtobufUtil.java
https://issues.redhat.com/browse/IPROTO-244
=> IPROTO-244 Do not pretty print JSON by default

core/src/main/java/org/infinispan/protostream/impl/JsonUtils.java, core/src/test/java/org/infinispan/protostream/ProtobufUtilTest.java
https://issues.redhat.com/browse/IPROTO-250
=> IPROTO-250 JSON incorrectly parses uint/fixed 32/64

parent/pom.xml
https://issues.redhat.com/browse/IPROTO-253
=> IPROTO-253 ProtoBuf 3.21.10

parent/pom.xml
https://issues.redhat.com/browse/IPROTO-253
Replaces #183
=> [4.5] IPROTO-253 ProtoBuf 3.21.10

core/pom.xml, core/src/main/java/org/infinispan/protostream/annotations/ProtoSchemaBuilder.java, integrationtests/pom.xml, parent/pom.xml, pom.xml, processor/pom.xml
https://issues.redhat.com/browse/IPROTO-254 Drop shading
https://issues.redhat.com/browse/IPROTO-255 Drop commons-cli
https://issues.redhat.com/browse/IPROTO-256 Javassist 3.29.1-GA
https://issues.redhat.com/browse/IPROTO-257 Jackson Core 2.14.1
https://issues.redhat.com/browse/IPROTO-258 Drop Google Protobuf
=> IPROTO-254 Drop shading

integrationtests/pom.xml, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/AnnotationProcessorCompilationTest.java, integrationtests/src/test/resources/org/infinispan/protostream/integrationtests/processor/CalculusAuto.java, integrationtests/src/test/resources/org/infinispan/protostream/integrationtests/processor/LongAuto.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/AutoProtoSchemaBuilderAnnotationProcessor.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/CompileTimeProtoSchemaGenerator.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/dependecy/CompileTimeDependency.java
https://issues.redhat.com/browse/IPROTO-260
=> IPROTO-260 Fix generation using dependent schemas

core/pom.xml, integrationtests/pom.xml, parent/pom.xml, pom.xml, processor/pom.xml, sample-domain-definition/pom.xml, sample-domain-implementation/pom.xml, types/pom.xml
Was not updated when 4.6.2 was tagged.
=> Next version 4.6.3-SNAPSHOT

core/src/main/java/org/infinispan/protostream/impl/TagReaderImpl.java
https://issues.redhat.com/browse/IPROTO-264
Reduces each invocation by 100-200 ns for relatively small objects
Ran from https://github.com/infinispan/infinispan-benchmarks/blob/main/protostream/src/main/java/org/infinispan/protostream/ProtostreamBenchmark.java
4.6.3-SNAPSHOT
```
Benchmark                                    (byteArrayOrStream)  Mode  Cnt     Score   Error  Units
ProtostreamBenchmark.testUnmarshallAddress                 false  avgt    6   340.235 ± 1.417  ns/op
ProtostreamBenchmark.testUnmarshallMetadata                false  avgt    6   537.461 ± 2.175  ns/op
ProtostreamBenchmark.testUnmarshallUser                    false  avgt    6  1057.641 ± 6.004  ns/op
```
4.6.2.Final
```
Benchmark                                    (byteArrayOrStream)  Mode  Cnt     Score   Error …
```
=> IPROTO-264 Remove stream buffer when unmarshalling objects

core/src/main/java/org/infinispan/protostream/impl/parser/AnnotationLexer.java, core/src/test/java/org/infinispan/protostream/impl/parser/AnnotationParserTest.java
https://issues.redhat.com/browse/IPROTO-275
=> IPROTO-275 Handle unicode escapes in annotations

.github/workflows/pull_requests.yml, .github/workflows/test_report.yaml, README.md, parent/pom.xml, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/GeneratedFilesWriter.java
https://issues.redhat.com/browse/IPROTO-277
=> IPROTO-277 Annotation parser breaks with JDK 17+

core/src/main/java/org/infinispan/protostream/impl/JsonUtils.java, core/src/test/java/org/infinispan/protostream/ProtobufUtilTest.java, core/src/test/java/org/infinispan/protostream/domain/Numerics.java, core/src/test/java/org/infinispan/protostream/domain/marshallers/MarshallerRegistration.java, core/src/test/java/org/infinispan/protostream/domain/marshallers/NumericsMarshaller.java, core/src/test/resources/sample_bank_account/bank.proto
https://issues.redhat.com/browse/IPROTO-280
Backport of #207.
=> [4.6.x] IPROTO-280 Byte and short not parsed into JSON

.github/workflows/pull_requests.yml, .github/workflows/release.yml, README.md, parent/pom.xml
https://issues.redhat.com/browse/IPROTO-302
=> IPROTO-302 Java 17

core/src/main/java/org/infinispan/protostream/descriptors/FieldDescriptor.java
https://issues.redhat.com/browse/IPROTO-241
=> IPROTO-241 Fix default values

core/src/main/java/org/infinispan/protostream/schema/CommentContainer.java, core/src/main/java/org/infinispan/protostream/schema/Enum.java, core/src/main/java/org/infinispan/protostream/schema/EnumContainer.java, core/src/main/java/org/infinispan/protostream/schema/EnumValue.java, core/src/main/java/org/infinispan/protostream/schema/Field.java, core/src/main/java/org/infinispan/protostream/schema/FieldContainer.java, core/src/main/java/org/infinispan/protostream/schema/GenericContainer.java, core/src/main/java/org/infinispan/protostream/schema/Map.java, core/src/main/java/org/infinispan/protostream/schema/Message.java, core/src/main/java/org/infinispan/protostream/schema/MessageContainer.java, core/src/main/java/org/infinispan/protostream/schema/OneOf.java, core/src/main/java/org/infinispan/protostream/schema/OptionContainer.java, core/src/main/java/org/infinispan/protostream/schema/ReservedContainer.java, core/src/main/java/org/infinispan/protostream/schema/Schema.java, core/src/main/java/org/infinispan/protostream/schema/SchemaWriter.java, core/src/main/java/org/infinispan/protostream/schema/Syntax.java, core/src/main/java/org/infinispan/protostream/schema/Type.java, core/src/test/java/org/infinispan/protostream/schema/ProtoBufSchemaTest.java
https://issues.redhat.com/browse/IPROTO-301
=> IPROTO-301 Schema API

.github/workflows/pull_requests.yml, .github/workflows/release.yml, .github/workflows/test_report.yaml, core/src/main/java/org/infinispan/protostream/MessageMarshaller.java, core/src/main/java/org/infinispan/protostream/descriptors/MapDescriptor.java, core/src/main/java/org/infinispan/protostream/impl/ProtoStreamReaderImpl.java, core/src/main/java/org/infinispan/protostream/impl/ProtoStreamWriterImpl.java, core/src/main/java/org/infinispan/protostream/impl/TagReaderImpl.java, core/src/main/java/org/infinispan/protostream/impl/TagWriterImpl.java, integrationtests/pom.xml, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/compliance/ComplianceTest.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/compliance/handwritten/CustomValue.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/compliance/handwritten/CustomValueMarshaller.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/compliance/handwritten/MapsTest.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/compliance/handwritten/MapsTestMarshaller.java, integrationtests/src/test/proto/maps.proto, parent/pom.xml
https://issues.redhat.com/browse/IPROTO-305
=> IPROTO-305 MessageMarshaller map support

core/src/main/javacc/org/infinispan/protostream/impl/parser/ProtoBuf.jj, core/src/test/java/org/infinispan/protostream/impl/parser/DescriptorsTest.java, core/src/test/resources/sample_bank_account/bank.proto
https://issues.redhat.com/browse/IPROTO-310
=> IPROTO-310 Fix multiple comments parsing

core/src/main/java/org/infinispan/protostream/annotations/impl/AbstractMarshallerCodeGenerator.java, core/src/test/java/org/infinispan/protostream/impl/parser/DescriptorsTest.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/AnnotationProcessorCompilationTest.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/GeneratedMarshallerTest.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/model/MapSchema.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/model/ModelWithMap.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/model/SimpleEnum.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/model/UUIDAdapter.java
https://issues.redhat.com/browse/IPROTO-319
=> IPROTO-319 Fix maps with non primitive values

.github/workflows/pull_requests.yml, types/pom.xml, types/src/main/java/org/infinispan/protostream/types/java/CommonTypes.java, types/src/main/java/org/infinispan/protostream/types/java/util/BitSetAdapter.java, types/src/test/java/org/infinispan/protostream/types/java/TypesMarshallingTest.java
https://issues.redhat.com/browse/IPROTO-318
=> IPROTO-318 Add support for BitSet

core/pom.xml, core/src/main/java/org/infinispan/protostream/FileDescriptorSource.java, core/src/main/java/org/infinispan/protostream/config/Configuration.java, core/src/main/java/org/infinispan/protostream/config/impl/ConfigurationImpl.java, core/src/main/java/org/infinispan/protostream/descriptors/Descriptor.java, core/src/main/java/org/infinispan/protostream/descriptors/EnumDescriptor.java, core/src/main/java/org/infinispan/protostream/descriptors/FileDescriptor.java, core/src/main/java/org/infinispan/protostream/descriptors/ProtoLock.java, core/src/main/java/org/infinispan/protostream/descriptors/ReservableDescriptor.java, core/src/main/java/org/infinispan/protostream/impl/JsonUtils.java, core/src/main/java/org/infinispan/protostream/impl/Log.java, core/src/main/java/org/infinispan/protostream/impl/SerializationContextImpl.java, core/src/main/java/org/infinispan/protostream/impl/SparseBitSet.java, core/src/main/java/org/infinispan/protostream/schema/ReservedNumbers.java, core/src/test/java/org/infinispan/protostream/ProtoLockTest.java, core/src/test/java/org/infinispan/protostream/SchemaEvolutionTest.java, core/src/test/java/org/infinispan/protostream/impl/parser/DescriptorsTest.java, core/src/test/resources/evolution/v1.proto, core/src/test/resources/evolution/v2.proto, core/src/test/resources/org/infinispan/protostream/test/message.proto, parent/pom.xml
https://issues.redhat.com/browse/IPROTO-322
based on https://github.com/infinispan/protostream/pull/256
=> IPROTO-322 Schema compatibility checks

core/src/main/java/org/infinispan/protostream/WrappedMessage.java, core/src/main/java/org/infinispan/protostream/config/Configuration.java, core/src/main/java/org/infinispan/protostream/config/impl/ConfigurationImpl.java, types/pom.xml, types/src/test/java/org/infinispan/protostream/types/java/Book.java, types/src/test/java/org/infinispan/protostream/types/java/BookSchema.java, types/src/test/java/org/infinispan/protostream/types/java/TypesMarshallingTest.java, types/src/test/resources/log4j2.xml
https://issues.redhat.com/browse/IPROTO-273
The third time is a charm... Change the code so the primitive collections/arrays aren't changed.
=> IPROTO-273 Elements in collections are not properly limited

core/src/main/java/org/infinispan/protostream/annotations/ProtoSchema.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/ProtoSchemaAnnotation.java
https://issues.redhat.com/browse/IPROTO-326
=> IPROTO-326 Add service attribute to ProtoSchema annotation

core/src/main/java/org/infinispan/protostream/ProtobufParser.java
I fixed a possible NPE in the parser.
=> IPROTO-344 NullPointerException in START_GROUP case parser

core/pom.xml, core/src/main/java/org/infinispan/protostream/descriptors/Descriptor.java, core/src/main/java/org/infinispan/protostream/descriptors/EnumDescriptor.java, core/src/main/java/org/infinispan/protostream/descriptors/ProtoLock.java, core/src/main/java/org/infinispan/protostream/impl/Log.java, core/src/test/java/org/infinispan/protostream/SchemaEvolutionTest.java, core/src/test/java/org/infinispan/protostream/impl/parser/DescriptorsTest.java, core/src/test/resources/evolution/v1.proto, core/src/test/resources/evolution/v2.proto, parent/pom.xml, processor/pom.xml
https://issues.redhat.com/browse/IPROTO-325
=> IPROTO-325 TypeId compatibility check

core/src/main/java/org/infinispan/protostream/BaseMarshaller.java, core/src/main/java/org/infinispan/protostream/GeneratedSchema.java, core/src/main/java/org/infinispan/protostream/annotations/ProtoAdapter.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoTypeMetadata.java, core/src/main/java/org/infinispan/protostream/descriptors/ResolutionContext.java, core/src/main/java/org/infinispan/protostream/impl/SerializationContextImpl.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/MarshallerSourceCodeGenerator.java, types/src/main/java/org/infinispan/protostream/types/java/CommonContainerTypes.java, types/src/main/java/org/infinispan/protostream/types/java/CommonTypes.java, types/src/main/java/org/infinispan/protostream/types/java/time/LocalDateAdapter.java, types/src/main/java/org/infinispan/protostream/types/java/time/LocalDateTimeAdapter.java, types/src/main/java/org/infinispan/protostream/types/java/time/LocalTimeAdapter.java, types/src/main/java/org/infinispan/protostream/types/java/time/MonthAdapter.java, types/src/main/java/org/infinispan/protostream/types/java/time/MonthDayAdapter.java, types/src/main/java/org/infinispan/protostream/types/java/time/OffsetTimeAdapter.java, types/src/main/java/org/infinispan/protostream/types/java/time/PeriodAdapter.java, types/src/main/java/org/infinispan/protostream/types/java/time/YearAdapter.java, types/src/main/java/org/infinispan/protostream/types/java/time/ZoneIdAdapter.java, types/src/main/java/org/infinispan/protostream/types/java/time/ZoneOffsetAdapter.java, types/src/main/java/org/infinispan/protostream/types/java/time/ZonedDateTimeAdapter.java, types/src/test/java/org/infinispan/protostream/types/java/BookSchema.java, types/src/test/java/org/infinispan/protostream/types/java/TypesMarshallingTest.java
https://issues.redhat.com/browse/IPROTO-146
=> IPROTO-146 Adapters for java.time classes

.github/workflows/pull_requests.yml, core/pom.xml, parent/pom.xml, types/pom.xml
https://issues.redhat.com/browse/IPROTO-348
=> IPROTO-348 Reproducible builds

core/src/main/java/org/infinispan/protostream/descriptors/ProtoLock.java, maven-plugin/README.md, maven-plugin/pom.xml, maven-plugin/src/main/java/org/infinispan/plugins/proto/compatibility/ProtoCompatibilityMojo.java, parent/pom.xml, pom.xml
https://issues.redhat.com/browse/IPROTO-355
https://issues.redhat.com/browse/IPROTO-356
=> IPROTO-355 Compatibility maven plugin + IPROTO-356 enum typeid proto.lock fix

maven-plugin/src/main/java/org/infinispan/plugins/proto/compatibility/ProtoCompatibilityMojo.java
https://issues.redhat.com/browse/IPROTO-384
=> IPROTO-384 Allow proto-schema-compatibility-maven-plugin to be skipped

.github/workflows/release.yml
https://issues.redhat.com/browse/IPROTO-363
=> IPROTO-363 Fix README.md updater

CODEOWNERS, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md, dco.txt
https://issues.redhat.com/browse/IPROTO-270
=> IPROTO-270 Add community docs

core/src/main/java/org/infinispan/protostream/annotations/AutoProtoSchemaBuilder.java, core/src/main/java/org/infinispan/protostream/annotations/impl/BaseProtoSchemaGenerator.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/AnnotationProcessorCompilationTest.java, integrationtests/src/test/resources/org/infinispan/protostream/integrationtests/processor/DependentInitializer.java, integrationtests/src/test/resources/org/infinispan/protostream/integrationtests/processor/DiscoveryWithoutAutoImport.java, integrationtests/src/test/resources/org/infinispan/protostream/integrationtests/processor/NestedDiscoveryWithoutAutoImport.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/AnnotatedClassScanner.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/AutoProtoSchemaBuilderAnnotationProcessor.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/CompileTimeProtoSchemaGenerator.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/ProtoSchemaAnnotation.java, processor/src/test/java/org/infinispan/protostream/annotations/impl/processor/tests/ProtoSchemaTest.java
https://issues.redhat.com/browse/IPROTO-158
=> IPROTO-158 Remove autoImportClasses

core/src/main/javacc/org/infinispan/protostream/impl/parser/ProtoBuf.jj, core/src/test/resources/sample_bank_account/bank.proto
=> 371 Allow "to" and "rpc" in identifier name

core/src/main/java/org/infinispan/protostream/annotations/impl/AbstractMarshallerCodeGenerator.java, core/src/test/java/org/infinispan/protostream/domain/Account.java, core/src/test/java/org/infinispan/protostream/domain/Pair.java, core/src/test/java/org/infinispan/protostream/domain/PairAdapter.java, core/src/test/java/org/infinispan/protostream/domain/User.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/performance/AnnotationsPerformanceTest.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/UserSerializationContextInitializer.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/types/MirrorTypeFactory.java
=> [#394] Don't use generics when marshalling collections

core/src/main/java/org/infinispan/protostream/annotations/impl/OriginatingClasses.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/AnnotatedClassScanner.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/AutoProtoSchemaBuilderAnnotationProcessor.java
=> [#408] Move OriginatingClasses annotation to protostream-core

core/src/main/java/org/infinispan/protostream/impl/ByteArrayOutputStreamEx.java
=> [#420] Deprecate ByteArrayOutputStreamEx

core/src/main/java/org/infinispan/protostream/annotations/impl/AbstractMarshallerCodeGenerator.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/annotated_package/package-info.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/GeneratedMarshallerTest.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/model/MapOverlappingMarshallerDelegate.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/model/MapSchema.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/MarshallerSourceCodeGenerator.java
=> [#418] Generated map marshallers always use __md$2 variable when initialising BaseMarshallerDelegate

core/src/main/java/org/infinispan/protostream/RandomAccessOutputStream.java, parent/pom.xml
=> [#435] Create source jars

parent/pom.xml
=> [#435] Always run source jar generation

core/src/main/java/org/infinispan/protostream/impl/Log.java, core/src/main/java/org/infinispan/protostream/impl/StringUtil.java, core/src/main/java/org/infinispan/protostream/impl/TagWriterImpl.java
=> [#447] Utilise String coder and value field to optimise writing of ASCII strings

.github/workflows/pull_requests.yml, .github/workflows/release.yml, .mvn/wrapper/maven-wrapper.properties, mvnw, mvnw.cmd, parent/pom.xml
=> [#460] Publish to Sonatype Central

types/src/main/java/module-info.java, types/src/main/java/org/infinispan/protostream/types/java/CommonContainerTypes.java, types/src/main/java/org/infinispan/protostream/types/java/CommonTypes.java, types/src/main/java/org/infinispan/protostream/types/protobuf/AnySchema.java, types/src/main/java/org/infinispan/protostream/types/protobuf/DurationSchema.java, types/src/main/java/org/infinispan/protostream/types/protobuf/EmptySchema.java, types/src/main/java/org/infinispan/protostream/types/protobuf/TimestampSchema.java, types/src/main/java/org/infinispan/protostream/types/protobuf/WrappersSchema.java
=> [#502] Export/open additional packages in protostream-types

maven-plugin/src/main/java/org/infinispan/plugins/proto/compatibility/ProtoCompatibilityMojo.java
=> Respect http_proxy and https_proxy env when performing remoteLockFile checks

maven-plugin/src/main/java/org/infinispan/plugins/proto/compatibility/ProtoCompatibilityMojo.java
=> [5.0.x] Respect http_proxy and https_proxy env when performing remoteLockFile checks

core/src/main/java/org/infinispan/protostream/WrappedMessage.java, core/src/main/java/org/infinispan/protostream/impl/TagReaderImpl.java
=> [#522] WrappedMessage should avoid byte[] allocation for inner message

core/src/main/java/org/infinispan/protostream/ImmutableSerializationContext.java, core/src/main/java/org/infinispan/protostream/WrappedMessage.java, core/src/main/java/org/infinispan/protostream/descriptors/ResolutionContext.java, core/src/main/java/org/infinispan/protostream/impl/SerializationContextImpl.java, core/src/main/java/org/infinispan/protostream/impl/SmallIntMap.java, core/src/test/java/org/infinispan/protostream/impl/parser/DescriptorsTest.java
* Condense id -> typeName -> marshaller to id -> marshaller lookup
* Add array based id optimization for small ids
Fixes #523
=> [#523] We should be able to optimize message id lookup

core/src/main/java/org/infinispan/protostream/GeneratedMarshallerBase.java, core/src/main/java/org/infinispan/protostream/TagReader.java, core/src/main/java/org/infinispan/protostream/annotations/ProtoSchema.java, core/src/main/java/org/infinispan/protostream/annotations/impl/AbstractMarshallerCodeGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/BaseProtoSchemaGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoMessageTypeMetadata.java, core/src/main/java/org/infinispan/protostream/descriptors/WireType.java, core/src/main/java/org/infinispan/protostream/impl/Log.java, core/src/main/java/org/infinispan/protostream/impl/TagReaderImpl.java, processor-tests/src/test/java/org/infinispan/protostream/processor/tests/OrderedMarshallerTest.java, processor-tests/src/test/java/org/infinispan/protostream/processor/tests/ProtoSchemaTest.java, processor-tests/src/test/java/org/infinispan/protostream/processor/tests/testdomain/MarshalledNo15GreaterThan.java, processor-tests/src/test/java/org/infinispan/protostream/processor/tests/testdomain/MarshalledYes15GreaterThan.java, processor/src/main/java/org/infinispan/protostream/processor/CompileTimeProtoSchemaGenerator.java, processor/src/main/java/org/infinispan/protostream/processor/ProtoSchemaAnnotation.java, processor/src/main/java/org/infinispan/protostream/processor/ProtoSchemaAnnotationProcessor.java
=> [#524] Add processor that creates an optimized marshaller

.github/workflows/pull_requests.yml, .github/workflows/test_report.yaml
fixes #495 
Introduced matrix strategy to test agains different jdk
Using same report action used in infinispan/infinispan
=> [#495] Reworked test CI

core/src/main/java/org/infinispan/protostream/SerializationContextInitializer.java, core/src/test/java/org/infinispan/protostream/ProtobufUtilTest.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/annotated_package/AnnotationOnPackageIntegrationTest.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/GeneratedMarshallerTest.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/transcoding/JSONTranscodingTest.java, processor-tests/src/test/java/org/infinispan/protostream/processor/tests/OrderedMarshallerTest.java, processor-tests/src/test/java/org/infinispan/protostream/processor/tests/ProtoSchemaTest.java, types/src/test/java/org/infinispan/protostream/types/java/JsonSerializationTest.java, types/src/test/java/org/infinispan/protostream/types/java/TypesMarshallingTest.java
=> [#546] SerializationContextIntializer.register()
