core/src/main/java/org/infinispan/protostream/annotations/impl/MarshallerCodeGenerator.java, core/src/test/java/org/infinispan/protostream/annotations/impl/ProtoSchemaBuilderTest.java
In the case of field optional and default value is specified, it seems would have been overwritten with default values.
For example, the following fields will be always the default value 23.
https://github.com/infinispan/protostream/blob/3.0.4.Final/core/src/test/java/org/infinispan/protostream/annotations/impl/testdomain/TestClass.java#L38
Code that is generated from this class, it seems it is also "__wasSet" by setting the value does not become true.
```java
final org.infinispan.protostream.annotations.impl.testdomain.TestClass o = new org.infinispan.protostream.annotations.impl.testdomain.TestClass();
boolean __wasSet$surname = false;
boolean __wasSet$age = false;
boolean __wasSet$color = false;
java.util.LinkedList __c$ints = null;
boolean __wasSet$x = false;
boolean …
```
=> fix optional and field with a default value

core/src/main/java/org/infinispan/protostream/MessageMarshaller.java, core/src/main/java/org/infinispan/protostream/impl/ProtoStreamWriterImpl.java, core/src/test/java/org/infinispan/protostream/domain/marshallers/UserMarshaller.java, sample-domain-implementation/src/main/java/org/infinispan/protostream/sampledomain/marshallers/UserMarshaller.java
* a deprecated method having a class parameter is still kept for backward compat
https://issues.jboss.org/browse/IPROTO-67
=> IPROTO-67 Remove the class parameter from ProtoStreamWriter.writeEnum

core/src/main/java/org/infinispan/protostream/annotations/ProtoBridgeFor.java, core/src/main/java/org/infinispan/protostream/annotations/impl/AbstractMarshallerCodeGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/BaseProtoSchemaGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/MarshallerByteCodeGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoMessageTypeMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoTypeMetadata.java, core/src/test/java/org/infinispan/protostream/annotations/impl/ProtoSchemaBuilderTest.java, core/src/test/java/org/infinispan/protostream/annotations/impl/testdomain/AddressBridge.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/AnnotationProcessorCompilationTest.java, integrationtests/src/test/resources/org/infinispan/protostream/integrationtests/processor/MarshallExternals.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/AnnotatedClassScanner.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/CompileTimeImportedProtoTypeMetadata.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/CompileTimeProtoMessageTypeMetadata.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/CompileTimeProtoSchemaGenerator.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/MarshallerSourceCodeGenerator.java
* introduce ProtoBridgeFor annotation to create annotation based
marshallers for peer classes that cannot be annotated
https://issues.redhat.com/browse/IPROTO-137
NOTE: ```ProtoBridgeFor```used to be named ```ProtoMarshallerFor``` until just now. I'm open for other name suggestions. Since the next release is an Alpha we can have it as is and rename it sometime before final.
=> IPROTO-137 Support Schema and Marshaller generation for external classes

core/src/main/java/org/infinispan/protostream/descriptors/FieldDescriptor.java, core/src/main/java/org/infinispan/protostream/descriptors/FileDescriptor.java, core/src/main/java/org/infinispan/protostream/descriptors/Type.java, core/src/test/java/org/infinispan/protostream/impl/TopLevelArrayTest.java
* Type.valueOf(typeName.toUpperCase()) was a huge mistake
https://issues.redhat.com/browse/IPROTO-208
=> IPROTO-208 Primitive types in proto files should not be case insensitive

core/src/main/java/org/infinispan/protostream/ProtobufUtil.java, core/src/main/java/org/infinispan/protostream/WrappedMessage.java, core/src/main/java/org/infinispan/protostream/impl/JsonUtils.java, core/src/main/java/org/infinispan/protostream/impl/TagWriterImpl.java, core/src/main/java/org/infinispan/protostream/impl/UnknownFieldSetImpl.java, core/src/test/java/org/infinispan/protostream/MarshallingTest.java, core/src/test/java/org/infinispan/protostream/impl/TagWriterImplTest.java
https://issues.redhat.com/browse/IPROTO-228
JMH benchmark results (https://github.com/pruivo/benchmarks/blob/main/protostream-jmh/src/main/java/me/pruivo/ProtostreamBenchmark.java#L59)
4.4.1.Final
```
Benchmark                                 Mode  Cnt     Score    Error  Units
ProtostreamBenchmark.testMarshallAddress  avgt    6   979.152 ±  7.242  ns/op
ProtostreamBenchmark.testMarshallUser     avgt    6  3398.020 ± 34.846  ns/op
```
This PR
```
Benchmark                                 Mode  Cnt     Score   Error  Units
ProtostreamBenchmark.testMarshallAddress  avgt    6   265.675 ± 2.005  ns/op
ProtostreamBenchmark.testMarshallUser     avgt    6  1257.325 ± 7.937  ns/op
```
=> IPROTO-228 Remove temporary buffers when marshalling objects

core/src/main/java/org/infinispan/protostream/annotations/impl/AbstractMarshallerCodeGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/MarshallerByteCodeGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/types/ReflectionTypeFactory.java, parent/pom.xml
https://issues.redhat.com/browse/IPROTO-230
=> IPROTO-230 Fix MarshallerByteCodeGenerator on JDK 17

core/src/main/java/org/infinispan/protostream/annotations/impl/MarshallerByteCodeGenerator.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/AutoProtoSchemaBuilderAnnotationProcessor.java
https://issues.redhat.com/browse/IPROTO-233
Supersedes https://github.com/infinispan/protostream/pull/157
Use `mvn clean install -Dorg.infinispan.protostream.skipAnnotationCompilerCheck` to build on JDK 8.
=> IPROTO-233 Fix MarshallerByteCodeGenerator on JDK 8 and 9+

core/pom.xml, integrationtests/pom.xml, parent/pom.xml, processor/pom.xml, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/AutoProtoSchemaBuilderAnnotationProcessor.java, types/pom.xml
https://issues.redhat.com/browse/IPROTO-239
=> IPROTO-239 Use correct generated class

parent/pom.xml
https://issues.redhat.com/browse/IPROTO-248
Details in JIRA description.
=> IPROTO-248 Make parent/pom.xml valid against Maven XSD

core/src/main/java/org/infinispan/protostream/Decoder.java, core/src/main/java/org/infinispan/protostream/Encoder.java, core/src/main/java/org/infinispan/protostream/ProtobufUtil.java, core/src/main/java/org/infinispan/protostream/TagReader.java, core/src/main/java/org/infinispan/protostream/TagWriter.java, core/src/main/java/org/infinispan/protostream/WrappedMessage.java, core/src/main/java/org/infinispan/protostream/annotations/impl/GeneratedMarshallerBase.java, core/src/main/java/org/infinispan/protostream/impl/ByteArrayOutputStreamEx.java, core/src/main/java/org/infinispan/protostream/impl/TagReaderImpl.java, core/src/main/java/org/infinispan/protostream/impl/TagWriterImpl.java, core/src/test/java/org/infinispan/protostream/ProtobufUtilTest.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/annotated_package/AnnotationOnPackageIntegrationTest.java
* Add new subWriter method to implement to allow reusing encoder instances
* Add some common default methods to the TagWriter/TagReader interfaces
* Add common way to write a fixed varint of 5 bytes
https://issues.redhat.com/browse/IPROTO-265
https://issues.redhat.com/browse/IPROTO-266
Also added changes to allow for custom Decoder/Encoder instances to be used instead of the supplied ones.
=> IPROTO-265 Remove additional byte[] allocations for nested writers

core/src/main/java/org/infinispan/protostream/impl/JsonUtils.java, core/src/test/java/org/infinispan/protostream/ProtobufUtilTest.java, core/src/test/java/org/infinispan/protostream/domain/Numerics.java, core/src/test/java/org/infinispan/protostream/domain/marshallers/MarshallerRegistration.java, core/src/test/java/org/infinispan/protostream/domain/marshallers/NumericsMarshaller.java, core/src/test/resources/sample_bank_account/bank.proto
https://issues.redhat.com/browse/IPROTO-280
The byte/short has a representation in protostream that knows the underlying type. In JSON, it becomes `{"_type":"int32","_value":1}`, but if we parse the JSON back to the protostream representation, the byte array is not the same, as it transforms the value into an int. TBH, I am unsure we can make the byte array the same without breaking compatibility. The problem is that the JSON representation loses the notion of the typing.
=> IPROTO-280 Byte and short not parsed into JSON

core/src/main/java/org/infinispan/protostream/annotations/Proto.java, core/src/main/java/org/infinispan/protostream/annotations/ProtoTypeId.java, core/src/main/java/org/infinispan/protostream/annotations/impl/AbstractMarshallerCodeGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoMessageTypeMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/types/XClass.java, core/src/main/java/org/infinispan/protostream/impl/Log.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/AnnotatedClassScanner.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/CompileTimeProtoMessageTypeMetadata.java, processor/src/test/java/org/infinispan/protostream/annotations/impl/processor/tests/ProtoSchemaTest.java, processor/src/test/java/org/infinispan/protostream/annotations/impl/processor/tests/testdomain/SimpleClass.java, processor/src/test/java/org/infinispan/protostream/annotations/impl/processor/tests/testdomain/SimpleRecord.java
https://issues.redhat.com/browse/IPROTO-307
https://issues.redhat.com/browse/IPROTO-306
Adds a `@Proto` annotation for simple handling of protobuf entities. Also adds support for Java `record`s
=> IPROTO-307 @Proto annotation

processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/AutoProtoSchemaBuilderAnnotationProcessor.java
The issue:
-  The value being generated for constant PROTO_SCHEMA was adding odd quotes in the middle of the string. So the generated value could not be compiled.
The cause: 
- The method makeStringLiteral, used to generate the value for PROTO_SCHEMA, was building the string iterating char by char and appending line breaks, slashes, quotes and plus signs in order to transform the string to literal keeping that as multi line.
Suggested fix: 
- The method was refactored to use java builtin multi-line string support with triple quotes (""" ..._multi line string here_... """). So, no need to escape line breaks any more.
=> fix: PROTO_SCHEMA generated value with unclosed string literal

core/src/main/java/org/infinispan/protostream/annotations/ProtoSchema.java, core/src/main/java/org/infinispan/protostream/annotations/impl/BaseProtoSchemaGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoMessageTypeMetadata.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/GeneratedMarshallerTest.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/model/FootballSchema.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/model/NullTestModel.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/model/Player.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/AutoProtoSchemaBuilderAnnotationProcessor.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/CompileTimeProtoSchemaGenerator.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/ProtoSchemaAnnotation.java
https://issues.redhat.com/browse/IPROTO-343
=> IPROTO-343 Allow null values for primitive types with PROTO3 syntax

core/src/main/java/org/infinispan/protostream/ProtobufParser.java, core/src/main/java/org/infinispan/protostream/descriptors/FieldDescriptor.java, core/src/main/java/org/infinispan/protostream/descriptors/MapDescriptor.java, core/src/main/java/org/infinispan/protostream/impl/JsonUtils.java, integrationtests/pom.xml, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/GeneratedMarshallerTest.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/model/MapOfMapOfUUID.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/model/MapOfString.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/model/MapOfUUID.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/model/MapSchema.java
https://issues.redhat.com/browse/IPROTO-346
=> ISPN-346 Fix JSON for maps

core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoMessageTypeMetadata.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/GeneratedMarshallerTest.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/model/FootballSchema.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/model/SimpleRecord.java
https://issues.redhat.com/browse/IPROTO-350
Requires https://github.com/infinispan/protostream/pull/291
=> IPROTO-350 Proto3 record default values initialized to null

core/src/main/java/org/infinispan/protostream/descriptors/FileDescriptor.java, core/src/main/java/org/infinispan/protostream/descriptors/ProtoLock.java, core/src/main/java/org/infinispan/protostream/impl/parser/ProtostreamProtoParser.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/GeneratedMarshallerTest.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/model/SimpleEnum.java
https://issues.redhat.com/browse/IPROTO-351
I don't know if this is the best way to do it and the method name is not the best. Suggestions are welcome.
=> IPROTO-351 TypeId must be parsed before the compatibility check

core/src/main/java/org/infinispan/protostream/impl/JsonUtils.java, core/src/main/java/org/infinispan/protostream/impl/RepeatedFieldDescriptor.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/model/Play.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/transcoding/JSONTranscodingTest.java
https://issues.redhat.com/browse/IPROTO-341
=> IPROTO-341 Transcode json array root object

.github/workflows/release.yml
currently, Git commit reference in release binaries output is one commit behind the Git tag, given the order of operation in the workflow
Git commit has to be done before building: perhaps it won't be pushed if build fails, but at least build references the right commit hash that will get tagged
issue found while trying to rebuild for Reproducible Builds: https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/infinispan/protostream/README.md
and more precisely analysis differences https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/infinispan/protostream/protostream-aggregator-5.0.7.Final.diffoscope
=> build from release commit

core/src/main/java/org/infinispan/protostream/annotations/impl/AbstractMarshallerCodeGenerator.java, core/src/test/java/org/infinispan/protostream/domain/Account.java, core/src/test/java/org/infinispan/protostream/domain/Pair.java, core/src/test/java/org/infinispan/protostream/domain/PairAdapter.java, core/src/test/java/org/infinispan/protostream/domain/User.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/performance/AnnotationsPerformanceTest.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/UserSerializationContextInitializer.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/types/MirrorTypeFactory.java
=> [#394] Don't use generics when marshalling collections

core/src/main/java/org/infinispan/protostream/annotations/ProtoField.java, core/src/main/java/org/infinispan/protostream/annotations/impl/AbstractMarshallerCodeGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoFieldMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoMapMetadata.java, core/src/main/java/org/infinispan/protostream/annotations/impl/ProtoMessageTypeMetadata.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/GeneratedMarshallerTest.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/model/IterableModel.java, integrationtests/src/test/java/org/infinispan/protostream/integrationtests/processor/marshaller/model/StreamModel.java, processor/src/main/java/org/infinispan/protostream/annotations/impl/processor/types/MirrorTypeFactory.java
=> [#416] Add support for Stream and Iterable to @ProtoField

parent/pom.xml
Closes #423 
Fixed the maven warnings and updated the plugins version to the latest. Most plugins require maven 3.6.3+, so I updated that in the enforcer. 
I used `versions:display-plugin-updates` to tell me the versions.
=> [#423] Remove jboss-parent

core/src/main/java/org/infinispan/protostream/RandomAccessOutputStream.java, core/src/main/java/org/infinispan/protostream/TagWriter.java, core/src/main/java/org/infinispan/protostream/WrappedMessage.java, core/src/main/java/org/infinispan/protostream/annotations/impl/AbstractMarshallerCodeGenerator.java, core/src/main/java/org/infinispan/protostream/annotations/impl/GeneratedMarshallerBase.java, core/src/main/java/org/infinispan/protostream/descriptors/WireType.java, core/src/main/java/org/infinispan/protostream/impl/ProtoStreamWriterImpl.java, core/src/main/java/org/infinispan/protostream/impl/RandomAccessOutputStreamImpl.java, core/src/main/java/org/infinispan/protostream/impl/TagWriterImpl.java, core/src/test/java/org/infinispan/protostream/ProtobufUtilTest.java
Fixes #427
This PR introduces a new method to TagWriter and Encoder to allow those classes control the TagWriter and Encoder that are created whenever a sub message is found. It removes all manual creations of TagWriters in those places and replaces with calls to the new method.
The first commit does that refactoring and by default has all Writer/Encoders use OutputStreamRandomAccessEncoder as was done prior. The big difference is the new encoders will cache previously used sub encoders so they will not have to recreate them for multiple nested messages at the same depth.
The second commit takes this one step further by introducing a move method to the RandomAccessOutputStream by allowing it to move bytes within the same stream. This allows us to not have to create any additional byte[] …
=> Optimize nested writers during marshalling.

parent/pom.xml
=> [#440] Simplify reproducible builds

core/src/main/java/org/infinispan/protostream/impl/TagWriterImpl.java
=> [#445] Encoder#subEncoder implementations can throw ArrayIndexOutOfBoundException

core/src/main/java/org/infinispan/protostream/RandomAccessOutputStream.java, core/src/main/java/org/infinispan/protostream/impl/RandomAccessOutputStreamImpl.java, core/src/main/java/org/infinispan/protostream/impl/TagReaderImpl.java, core/src/main/java/org/infinispan/protostream/impl/TagWriterImpl.java, core/src/main/java/org/infinispan/protostream/impl/VarHandlesUtil.java
Closes #452 
The JMH Result using the UUID (uses 2 fixed 64 bits) shows improvements around 3%~14% when compared with 6.0.0.Dev06
```
-- This Pull Request
Benchmark                                      (byteArrayOrStream)  Mode  Cnt    Score   Error  Units
ProtostreamBenchmark.testMarshallUUID                         true  avgt    6  193.928 ± 5.406  ns/op
ProtostreamBenchmark.testMarshallUUID:async                   true  avgt           NaN            ---
ProtostreamBenchmark.testMarshallUUID                        false  avgt    6   46.885 ± 2.137  ns/op
ProtostreamBenchmark.testMarshallUUID:async                  false  avgt           NaN            ---
ProtostreamBenchmark.testSizedUUID                            true  avgt    6   40.430 ± 2.213  ns/op …
```
=> [#452] Use VarHandle to write fixed 32 and 64 bit value

core/src/main/java/org/infinispan/protostream/WrappedMessage.java, core/src/main/java/org/infinispan/protostream/impl/JsonUtils.java, types/src/main/java/org/infinispan/protostream/types/java/CommonTypes.java, types/src/main/java/org/infinispan/protostream/types/java/time/DateAdapter.java, types/src/main/java/org/infinispan/protostream/types/java/time/InstantAdapter.java, types/src/test/java/org/infinispan/protostream/types/java/TypesMarshallingTest.java
Backporting just the specific changes to Instant and Date from #411.
=> [5.0.x] [#405] Backport JSON parse for Instant

core/src/main/java/org/infinispan/protostream/impl/json/JsonHelper.java, core/src/main/java/org/infinispan/protostream/impl/json/ObjectJsonWriter.java, core/src/test/java/org/infinispan/protostream/ProtobufUtilTest.java
* Do not require a marshaller to be registered.
Closes #487.
=> [#487] JSON serialization use only descriptor

core/src/main/java/org/infinispan/protostream/GeneratedSchema.java, core/src/main/java/org/infinispan/protostream/schema/Schema.java, core/src/main/java/org/infinispan/protostream/schema/SchemaByBuilder.java, core/src/main/java/org/infinispan/protostream/schema/SchemaByString.java, core/src/main/java/org/infinispan/protostream/schema/SchemaWriter.java, core/src/test/java/org/infinispan/protostream/schema/ProtoBufSchemaTest.java
We use in many cases "string" "string" for our tests and more (since we were using the put api most of the time directly in the internal cache in Infinispan.
The idea is to be able to do:
```java
private static final String SCHEMA_NAME = "my-schema.proto";
Schema goodSchema = Schema.buildFromStringContent(SCHEMA_NAME, ResourceUtils.getResourceAsString(getClass(), "/proto/ciao.proto"));
Schema wrongSchema = Schema.buildFromStringContent(SCHEMA_NAME, ResourceUtils.getResourceAsString(getClass(), "/proto/ciao-wrong.proto"));
remoteCacheManager.administration().schemas().createOrUpdate(goodSchema);
///
remoteCacheManager.administration().schemas().createOrUpdate(wrongSchema);
```
Also GeneratedSchema to be Schema helps
=> Add Schema created by String content
